### ISSUE TITLE
Bug: Noise in rendering with Intel Graphics

### ISSUE THREAD

**Issue by Mardanshahi** [PacktPublishing/OpenGL-Build-High-Performance-Graphics#1]
I want to report some of module 1 chapter 7 project have issues with Intel GPUs based on my experience. I tested all of chapter 7 projects on Windows 10 with Nvidia GTX 1060 and Intel HD Graphics 630. "3DTextureSlicingClassification" and "3DTextureSlicing" was the only projects that works correctly on both Intel and NVIDIA GPUs. In my tests the following projects had artifacts and noise:
   
GPURaycasting
GPURaycastingIsosurface
HalfAngleSlicing
MarchingTetrahedra
Splatting

HalfAngleSlicing Output with Nvidia Graphics:
![2023-02-09 13_22_14-GPURaycasting - Microsoft Visual Studio](https://user-images.githubusercontent.com/7051060/217784159-4050fdd8-112d-44ab-8067-07dcfb51bdc1.png)

HalfAngleSlicing Output with Intel Graphics:
![2023-02-09 13_02_56-OpenGL - Build High Performance - Muhammad Mobeen Movania,David W pdf and 13 mor](https://user-images.githubusercontent.com/7051060/217784261-6f5baa2d-30e7-432d-9b92-529f8f39bdb6.png)

Does anyone knows how I can fix that issue for Intel Graphics?

**Comment by mmmovania** [comment]
Hi there apologies for the delay. I am the author of the book chapter and codes.
   To debug this, I would like to know some more details about your Intel GPU. 
1) Are your Intel drivers updated? If not please update them and then try the code.
2) The share dataset seems to be different from the one that is shipped with the book. Can you share the output that is produced from the demo engine dataset that ships with the demo code? Does it also produce these artifacts or is it for you own dataset only? If so then I would suggest you check that the 3D texture format (internal and format fields of 3dTexture) and data types used both in the texture creation (glTexImage3D) as well as in the shader are of appropriate texture datatype.
3) Are you running the code in the debug or the release build? If in release build, can you switch to debug build and see if the console is clean (that is without any logs or warnings).
4) The output suggests some issue with the blending of slices. Could very well be that the texture format is not supported or some other thing. 
5) Can you try changing the texture filtering from GL_LINEAR to GL_NEAREST and see if it helps?

These are some of the things that come to my mind. I can guide further if you share the answers of the above.

**Comment by Mardanshahi** [comment]
First of all I forked the repo and made my commits. you are welcome to check it out:
https://github.com/Mardanshahi/OpenGL-Build-High-Performance-Graphics-Improved

I examined your suggestions and questions and these are my answers for them:

1. I compiled and examined the code in two Windows devices. First on a Laptop with a Intel HD Graphics 630 GPU and second on a Windows PC with a Intel HD Graphics 530 GPU and both of theme are updated to their latest drivers. Unfortunately in both cases I have the same noisy unacceptable results. On the other hand I want my application to be compatible as high as possible with old drivers and GPUs. So I prefer to improve the algorithm instead of upgrading the hardware.

2. The original dataset (Engine256.raw) and my dataset are tested and both have the same results. here it is the output of Engine256.raw
![Engine256 raw](https://user-images.githubusercontent.com/7051060/222057808-f86a8770-b2dc-4ff2-9dcd-2222d2c4fc66.png)

3. I compiled the code in both debug and release mode and unfortunately they have same results.
4. I am agree with you that something is wrong with blending of slices but I don't understand your point about texture format is not supported. 
5. I changed the texture filtering from GL_LINEAR to GL_NEAREST and nothing changed in the output.

**Comment by mmmovania** [comment]
One more question that I have. Does this happen with the original unmodified code also? Can you try running the unmodified code to see if you get the same result as what is shown in the book chapter?

**Comment by Mardanshahi** [comment]
I cloned a fresh repo as you wanted and I executed the project "GPURaycasting" on my Laptop. I got an error on the file main.cpp line 74 as shown in picture below:
![glTexParameteri-Error](https://user-images.githubusercontent.com/7051060/222518308-fe6f6222-e221-4d50-8530-efff92a62aad.png)
![error](https://user-images.githubusercontent.com/7051060/222520745-fd68dfde-2fef-4d84-bf3a-db62e778fc88.png)

I want to mention again that I tested the sample "GPURaycasting" On both Nvidia and Intel GPU (My Laptop has both of them and I can switch between them) and I just got error on Intel.

**Comment by Mardanshahi** [comment]
Update 1: In the project "GPURaycasting" I removed all "GL_CHECK_ERRORS" lines from main.cpp **temporary** and I got the same noisy output you saw in the first issue.

Update 2: This error also happens in "3DTextureSlicing" and "3DTextureSlicingClassification" projects however they show the output correct and without any noise.

**Comment by mmmovania** [comment]
The GL_CHECK_ERRORS shoud not be remove since this is reporting some issue with the OpenGL error bit. Can you please insert the GL_CHECK_ERRORS call before the glGenTExtures call after the file is read. I suspect it could be that the error is raised before the code comes to the texture loading.

**Comment by Mardanshahi** [comment]
This is a fresh clone. I did not remove GL_CHECK_ERRORS lines.

**Comment by Mardanshahi** [comment]
"please insert the GL_CHECK_ERRORS call before the glGenTExtures call "; So I changed the code like this:
![error line number](https://user-images.githubusercontent.com/7051060/222955074-7628792e-9a6c-4306-bfb9-9b5fa4a9bc31.png)


As you can see the error raised form "glTexParameteri()".

**Comment by mmmovania** [comment]
Ok I was able to replicate the issue and solve it. Following are the changes that you need to do in lines 73-76 in main.cpp.
1) replace GL_CLAMP with GL_CLAMP_TO_EDGE
```
// set the texture parameters
glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE); 
glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
```

2) In raycaster.frag fragment shader, initialize the vFragColor to vec4(0,0,0,0);

```
void main()
{ 
	//get the 3D texture coordinates for lookup into the volume dataset
	vec3 dataPos = vUV;
	 
        //initialize the vFragColor to vec4(0,0,0,0)
	vFragColor = vec4(0,0,0,0);
        
        //rest of the shader code

```
I was able to get correct result on my laptop with Intel UHD 620 GPU
![image](https://user-images.githubusercontent.com/1354859/222957590-ad1403bc-41a7-4f14-85bc-2ed5107e4299.png)

**Comment by Mardanshahi** [comment]
Yes, it fixed the problem!
I a going to test this solution with the rest of the chapter 7 projects.
Thank you a lot ❤️

**Comment by mmmovania** [comment]
No problem I am glad I could be of help. Please close this issue for now. If there is anything else, open a new issue.

**Comment by Mardanshahi** [comment]
Sure. Thank you.
